# Generated by Django 5.1.5 on 2025-01-19 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('publication_date', models.CharField(blank=True, max_length=50, null=True)),
                ('quarter', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('phic_number', models.CharField(blank=True, max_length=30, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('nature_of_employment', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('plantilla_item_no', models.CharField(max_length=100, unique=True)),
                ('salary_grade', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('Vacant', 'Vacant'), ('For Selection', 'For Selection'), ('For Assumption', 'For Assumption'), ('Reposted-For Exam', 'Reposted-For Exam'), ('For Interview', 'For Interview'), ('For Deliberation', 'For Deliberation'), ('Filled', 'Filled'), ('Retired', 'Retired'), ('Hold', 'Hold')], default='Vacant', max_length=50)),
                ('date_of_publication', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('target_date_of_appointment', models.DateField(blank=True, null=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='position_app.division')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='position_app.position'),
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('current_stage', models.CharField(choices=[('Document Review', 'Document Review'), ('Examination', 'Examination'), ('Interview', 'Interview'), ('Deliberation', 'Deliberation'), ('Final Appointment', 'Final Appointment')], default='Document Review', max_length=50)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('position_applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position_app.position')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='recruitment_docs/')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position_app.applicant')),
            ],
        ),
    ]
